### ISSUE TITLE
Missing 'parent' of BladeController in BladeRack.add

### ISSUE THREAD

**Issue by antlii** [doersino/tweakpane-plugin-infodump#2]
I tried to use your fantastic plugin, but unfortunately, there are incompatibilities with the current version of Tweakpane:
_Missing 'parent' of BladeController in BladeRack.add. Please rebuild plugins with the latest core package._

Is there any chance that you will update the plugin in the near future?
Thanks!

**Comment by doersino** [comment]
That seems to be a recent change: https://github.com/cocopon/tweakpane/blame/35d43c761a3015b9b2a863528c69e6427b9f9b18/packages/core/src/blade/common/controller/blade.ts#L55

I'll try and add that method to my `InfodumpController` – working on it now.

**Comment by antlii** [comment]
Awesome, thanks for the support!

**Comment by doersino** [comment]
Okay, I think it should work now – all I had to was was up the Tweakpane dependency and build a new release, it seems. Try the new release: https://github.com/doersino/tweakpane-plugin-infodump/releases/tag/v0.3.0

**Comment by antlii** [comment]
Oh, thank you so much for the quick fix! Much appreciated! ;)
